/** GENERATED by tools/gamelib/generate.mjs — do not edit by hand. */
export const LIBRARY_GAMES = [
  {
    "slug": "snake-classic",
    "ar": "الثعبان الكلاسيكي",
    "en": "Classic Snake",
    "description": "النسخة التي يعرفها الجميع: قُد الثعبان نحو التفاح دون أن يعضّ ذيله. كل تفاحة تطيله خطوة وتضيف عشر نقاط.",
    "descriptionEn": "Classic Snake — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب لتغيير الاتجاه. الالتفاف حول الحواف مسموح، لكن الاصطدام بالجسد أو بالجدران ينتهي اللعبة.",
    "categories": [
      "arcade",
      "classic"
    ],
    "tags": [
      "snake",
      "classic",
      "retro"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 560,
    "height": 560,
    "sizeKb": 6,
    "featured": true,
    "plays": 1840,
    "rating": 4.2
  },
  {
    "slug": "snake-turbo",
    "ar": "الثعبان توربو",
    "en": "Turbo Snake",
    "description": "الثعبان نفسه بسرعة مضاعفة وشبكة أوسع: انعكاسات أسرع من أن تفكر فيها. للاعبين ذوي الأعصاب الباردة فقط.",
    "descriptionEn": "Turbo Snake — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب. السرعة هنا أعلى من النسخة الكلاسيكية بمرتين — خطط لمسارك قبل أن تحتاجه.",
    "categories": [
      "arcade",
      "action"
    ],
    "tags": [
      "snake",
      "fast",
      "neon"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 7,
    "featured": false,
    "plays": 5267,
    "rating": 4.5
  },
  {
    "slug": "snake-maze",
    "ar": "ثعبان المتاهة",
    "en": "Maze Snake",
    "description": "جدران صلبة تقطع الملعب إلى ممرات: الثعبان الكلاسيكي يصبح لغزًا حركيًا حيث كل منعطف قرار.",
    "descriptionEn": "Maze Snake — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب. الجدران الزرقاء قاتلة مثل ذيلك تمامًا — استخدم الممرات الأربعة بحذر.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "snake",
      "maze",
      "hard"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 8,
    "featured": false,
    "plays": 9194,
    "rating": 4.7
  },
  {
    "slug": "snake-kids",
    "ar": "ثعبان الأطفال",
    "en": "Kids Snake",
    "description": "شبكة كبيرة وخيوط بطيئة وألوان حلوى: أول ثعبان يصلح لطفل يتعلم الأسهم اليوم.",
    "descriptionEn": "Kids Snake — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب على الشاشة. اللعبة متسامحة: شبكة واسعة وسرعة هادئة.",
    "categories": [
      "kids",
      "mobile"
    ],
    "tags": [
      "snake",
      "kids",
      "easy"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 9,
    "featured": false,
    "plays": 2711,
    "rating": 4
  },
  {
    "slug": "brick-blaster",
    "ar": "محطّم الطوب",
    "en": "Brick Blaster",
    "description": "مضرب وكرة وخمسة صفوف من الطوب: فيزياء بسيطة وإدمان خالص. الزوايا التي تضرب بها الكرة تصنعها أنت.",
    "descriptionEn": "Brick Blaster — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "حرّك المضرب بالفأرة أو اللمس أو الأسهم. أصب الطوب كله لتفوز، ولا تدع الكرة تسقط.",
    "categories": [
      "arcade",
      "classic"
    ],
    "tags": [
      "breakout",
      "bricks",
      "classic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 520,
    "sizeKb": 10,
    "featured": false,
    "plays": 15548,
    "rating": 4.8
  },
  {
    "slug": "brick-candy",
    "ar": "طوب الحلوى",
    "en": "Candy Bricks",
    "description": "نسخة بطيئة وملوّنة من محطّم الطوب بمضرب عريض: مثالية للأطفال وأول تجربة مع ألعاب الفيزياء.",
    "descriptionEn": "Candy Bricks — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "حرّك المضرب باللمس أو الفأرة. أربعة صفوف فقط ومضرب واسع — لكنه يتطلّب دقة nonetheless.",
    "categories": [
      "kids",
      "arcade"
    ],
    "tags": [
      "breakout",
      "kids",
      "colorful"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 520,
    "sizeKb": 11,
    "featured": false,
    "plays": 7485,
    "rating": 4.3
  },
  {
    "slug": "brick-storm",
    "ar": "عاصفة الطوب",
    "en": "Brick Storm",
    "description": "سبعة صفوف، كرة أسرع، ومضرب أضيق: نسخة الاختبار التي تفصل لاعب الطوب عن هاويه.",
    "descriptionEn": "Brick Storm — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الفأرة أو اللمس. كل ارتداد من طرف المضرب يضيف زاوية للكرة — استخدمها عمدًا.",
    "categories": [
      "action",
      "arcade"
    ],
    "tags": [
      "breakout",
      "hard",
      "fast"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 520,
    "sizeKb": 12,
    "featured": false,
    "plays": 4322,
    "rating": 4.6
  },
  {
    "slug": "pong-duel",
    "ar": "بونج ضد الحاسوب",
    "en": "Pong Duel",
    "description": "أقدم مباراة في تاريخ ألعاب الفيديو: أنت والحاسوب وسبع نقاط تفصل بينكما. الخصم يتحسّن كلما طال rally.",
    "descriptionEn": "Pong Duel — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "حرّك مضربك بالفأرة أو اللمس أو السهمين. أول من يصل إلى سبع نقاط يفوز.",
    "categories": [
      "sports",
      "two-player"
    ],
    "tags": [
      "pong",
      "ai",
      "classic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 480,
    "sizeKb": 6,
    "featured": false,
    "plays": 11459,
    "rating": 4.1
  },
  {
    "slug": "pong-rookie",
    "ar": "بونج للمبتدئين",
    "en": "Pong Rookie",
    "description": "خصم لطيف ومضرب عريض وخمس نقاط فقط: تعلّم البونج دون إحباط.",
    "descriptionEn": "Pong Rookie — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الفأرة أو اللمس أو الأسهم. خمس نقاط تنهي المباراة.",
    "categories": [
      "kids",
      "sports"
    ],
    "tags": [
      "pong",
      "easy",
      "kids"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 480,
    "sizeKb": 7,
    "featured": false,
    "plays": 3596,
    "rating": 4.4
  },
  {
    "slug": "pong-pro",
    "ar": "بونج المحترفين",
    "en": "Pong Pro",
    "description": "كرة بسرعة جنونية وخصم لا يخطئ تقريبًا ومضرب بحجم إصبع: تحدي البونج النهائي.",
    "descriptionEn": "Pong Pro — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الفأرة أو اللمس. تسع نقاط للفوز — ولن تحصل عليها بسهولة.",
    "categories": [
      "sports",
      "action"
    ],
    "tags": [
      "pong",
      "hard",
      "reflex"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 720,
    "height": 480,
    "sizeKb": 8,
    "featured": true,
    "plays": 8933,
    "rating": 4.9
  },
  {
    "slug": "volt-2048-merge",
    "ar": "دمج ٢٠٤٨",
    "en": "Merge 2048",
    "description": "ادفع البلاطات واجمع المتشابهين حتى تولد بلاطة ٢٠٤٨. لعبة تبدو حسابية وهي في الحقيقة تخطيط للمساحة.",
    "descriptionEn": "Merge 2048 — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب على الشاشة. كل دفعة تحرك كل البلاطات، وكل دمج يضيف نقاطًا.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "2048",
      "merge",
      "math"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 520,
    "height": 560,
    "sizeKb": 9,
    "featured": false,
    "plays": 2470,
    "rating": 4.2
  },
  {
    "slug": "volt-1024-mini",
    "ar": "دمج ١٠٢٤ المصغّر",
    "en": "Mini 1024",
    "description": "شبكة ٣×٣ وهدف ١٠٢٣: نسخة الجيب السريعة من لعبة الدمج، تنتهي جولتها في دقيقتين.",
    "descriptionEn": "Mini 1024 — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب. المساحة الضيقة تعني أن كل حركة خطأ قاتلة.",
    "categories": [
      "kids",
      "puzzle"
    ],
    "tags": [
      "2048",
      "mini",
      "easy"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 560,
    "sizeKb": 10,
    "featured": false,
    "plays": 6807,
    "rating": 4.5
  },
  {
    "slug": "volt-4096-titan",
    "ar": "دمج ٤٠٩٦ تيتان",
    "en": "Titan 4096",
    "description": "شبكة ٥×٥ وهدف ٤٠٩٦: مساحة أوسع تعني احتمالات أكثر وقرارات أصعب. للاعبين الذين أنهوا ٢٠٤ ولم يشبعوا.",
    "descriptionEn": "Titan 4096 — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "الأسهم أو السحب. خطط لزوايا الدمج مبكرًا — الشبكة الكبيرة تخدع.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "2048",
      "hard",
      "5x5"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 560,
    "sizeKb": 11,
    "featured": false,
    "plays": 2284,
    "rating": 4.7
  },
  {
    "slug": "memory-zoo",
    "ar": "ذاكرة الحيوانات",
    "en": "Animal Memory",
    "description": "اقلب البطاقات واعثر على الأزواج: اثنا عشر حيوانًا يختبئون في شبكة، وذاكرتك هي الأداتك الوحيدة.",
    "descriptionEn": "Animal Memory — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط بطاقة لقلبها، ثم ثانية. إن تطابقتا بقيتا مكشوفتين. أقل محاولات = نتيجة أفضل.",
    "categories": [
      "kids",
      "brain"
    ],
    "tags": [
      "memory",
      "animals",
      "kids"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 600,
    "height": 560,
    "sizeKb": 12,
    "featured": false,
    "plays": 5711,
    "rating": 4
  },
  {
    "slug": "memory-fruits",
    "ar": "ذاكرة الفواكه",
    "en": "Fruit Memory",
    "description": "نسخة الفواكه المنعشة من لعبة الذاكرة: ألوان زاهية تساعد العين وتخادع الذاكرة في الوقت نفسه.",
    "descriptionEn": "Fruit Memory — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط لقلب بطاقتين. الأزواج المتطابقة تبقى مكشوفة حتى إنهاء اللوح.",
    "categories": [
      "kids",
      "puzzle"
    ],
    "tags": [
      "memory",
      "fruits",
      "family"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 600,
    "height": 560,
    "sizeKb": 6,
    "featured": false,
    "plays": 9638,
    "rating": 4.8
  },
  {
    "slug": "memory-space",
    "ar": "ذاكرة الفضاء",
    "en": "Space Memory",
    "description": "كواكب ومذنّبات ومخلوقات: لوحة ذاكرة بطابع فضائي لمن يحفظ النجوم أسرع من زملائه.",
    "descriptionEn": "Space Memory — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اقلب بطاقتين في كل دور. طابق كل الأزواج لتنهي الجولة.",
    "categories": [
      "adventure",
      "brain"
    ],
    "tags": [
      "memory",
      "space"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 600,
    "height": 560,
    "sizeKb": 7,
    "featured": false,
    "plays": 3155,
    "rating": 4.3
  },
  {
    "slug": "memory-math",
    "ar": "ذاكرة الأرقام",
    "en": "Number Memory",
    "description": "رموز العمليات الحسابية بدل الصور: نسخة المدرسين من لعبة الذاكرة، وأصعب مما تبدو.",
    "descriptionEn": "Number Memory — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اقلب وطابق الرموز المتشابهة. ستكتشف أن الرموز المجردة أصغر على الذاكرة من الصور.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "memory",
      "math",
      "school"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 600,
    "height": 560,
    "sizeKb": 8,
    "featured": false,
    "plays": 15992,
    "rating": 4.6
  },
  {
    "slug": "whack-mole",
    "ar": "اضرب الخلد",
    "en": "Whack-a-Mole",
    "description": "ثلاثون ثانية وتسع جحور وخلد واحد سريع: اختبر سرعة إصبعك في كلاسيكية الملاهي.",
    "descriptionEn": "Whack-a-Mole — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط على الخلد حين يظهر. كل إصابة نقطة، والوقت لا يرحم.",
    "categories": [
      "kids",
      "arcade"
    ],
    "tags": [
      "whack",
      "reflex",
      "classic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 9,
    "featured": false,
    "plays": 7929,
    "rating": 4.1
  },
  {
    "slug": "whack-alien",
    "ar": "اصطد الفضائي",
    "en": "Alien Whack",
    "description": "غزاة صغار يطلّون من فوهات الفضاء: نسخة أسرع وأقسى من اضرب الخلد.",
    "descriptionEn": "Alien Whack — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط الفضائي قبل أن يختفي. الظهور هنا أقصر من نسخة الخلد.",
    "categories": [
      "action",
      "arcade"
    ],
    "tags": [
      "whack",
      "space",
      "fast"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 10,
    "featured": true,
    "plays": 4766,
    "rating": 4.4
  },
  {
    "slug": "whack-robot",
    "ar": "أوقف الروبوت",
    "en": "Robot Whack",
    "description": "روبوتات متمردة تومض لأقل من نصف ثانية: الوضع الأقصى لسلسلة اضرب-واختفِ.",
    "descriptionEn": "Robot Whack — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "عشرون ثانية فقط. ردّة فعلك هي كل ما تملك.",
    "categories": [
      "action",
      "shooting"
    ],
    "tags": [
      "whack",
      "robots",
      "extreme"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 11,
    "featured": false,
    "plays": 11903,
    "rating": 4.9
  },
  {
    "slug": "flappy-volt",
    "ar": "الطائر الفولتي",
    "en": "Flappy Volt",
    "description": "نقرة واحدة للرفرفة وأنابيب لا تنتهي: أبسط تحكم في الموقع وأكثره إدمانًا.",
    "descriptionEn": "Flappy Volt — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط أو مسطرة المسافة للرفرفة. مرّ بين الأنابيب لتسجل نقطة لكل بوابة.",
    "categories": [
      "arcade",
      "mobile"
    ],
    "tags": [
      "flappy",
      "one-button",
      "hard"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 520,
    "height": 640,
    "sizeKb": 12,
    "featured": false,
    "plays": 4040,
    "rating": 4.2
  },
  {
    "slug": "rocket-rise",
    "ar": "ارتفاع الصاروخ",
    "en": "Rocket Rise",
    "description": "صاروخ بفوهات حساسة وفجوات أضيق: نسخة الفضاء من mechanics الرفرفة، بثوب نيون.",
    "descriptionEn": "Rocket Rise — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "نقرة = دفعة. الفجوات هنا أضيق والأنابيب أسرع من النسخة الكلاسيكية.",
    "categories": [
      "action",
      "adventure"
    ],
    "tags": [
      "flappy",
      "space",
      "rocket"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 640,
    "sizeKb": 6,
    "featured": false,
    "plays": 9377,
    "rating": 4.5
  },
  {
    "slug": "balloon-sky",
    "ar": "بالون السماء",
    "en": "Balloon Sky",
    "description": "بالون لطيف وفجوات واسعة وجاذبية رحيمة: مدخل الأطفال إلى عائلة الرفرفة.",
    "descriptionEn": "Balloon Sky — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط ليرتفع البالون. المسافة بين السحب واسعة لتناسب الصغار.",
    "categories": [
      "kids",
      "mobile"
    ],
    "tags": [
      "flappy",
      "kids",
      "easy"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 640,
    "sizeKb": 7,
    "featured": false,
    "plays": 2914,
    "rating": 4.7
  },
  {
    "slug": "desert-dash",
    "ar": "عدو الصحراء",
    "en": "Desert Dash",
    "description": "اركض بين صبار الصحراء ونسورها: قفز فوق الأرضي وانحنِ تحت الطائر، والسرعة تزيد كل ثوانٍ.",
    "descriptionEn": "Desert Dash — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "نقرة/مسطرة للقفز، ونقرة على أسفل الشاشة أو السهم الأسفل للانزلاق.",
    "categories": [
      "racing",
      "action"
    ],
    "tags": [
      "runner",
      "endless",
      "jump"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 760,
    "height": 420,
    "sizeKb": 8,
    "featured": false,
    "plays": 7251,
    "rating": 4
  },
  {
    "slug": "neon-runner",
    "ar": "عدّاء النيون",
    "en": "Neon Runner",
    "description": "مدينة نيون وأطباق طائرة وحواجز: نسخة أسرع من العدو اللانهائي بإيقاع لا يهدأ.",
    "descriptionEn": "Neon Runner — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اقفز بالحواجز الأرضية وانزلق تحت الأطباق. السرعة تتصاعد تلقائيًا.",
    "categories": [
      "racing",
      "arcade"
    ],
    "tags": [
      "runner",
      "neon",
      "fast"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 760,
    "height": 420,
    "sizeKb": 9,
    "featured": false,
    "plays": 2728,
    "rating": 4.8
  },
  {
    "slug": "jungle-jump",
    "ar": "قفز الغابة",
    "en": "Jungle Jump",
    "description": "قرد وصخور وخفافيش: عدو غابة بوتيرة ألطف تناسب اللاعبين الصغار والمبتدئين.",
    "descriptionEn": "Jungle Jump — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "نقرة للقفز فوق الصخور، ونقرة سفلية للانزلاق تحت الخفافيش.",
    "categories": [
      "kids",
      "adventure"
    ],
    "tags": [
      "runner",
      "jungle",
      "family"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 760,
    "height": 420,
    "sizeKb": 10,
    "featured": false,
    "plays": 6155,
    "rating": 4.3
  },
  {
    "slug": "mine-sweeper-easy",
    "ar": "كانس الألغام المبتدئ",
    "en": "Minesweeper Easy",
    "description": "تسعٌ في تسعة وعشرة ألغام: المنطق الخالص في أنقى صوره — الأرقام تخبرك وأنت تستنتج.",
    "descriptionEn": "Minesweeper Easy — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "انقر لفتح خلية، وزر الفأرة الأيمن (أو Alt مع اللمس) لوضع علم. أول نقرة آمنة دائمًا.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "minesweeper",
      "logic",
      "classic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 11,
    "featured": false,
    "plays": 10082,
    "rating": 4.6
  },
  {
    "slug": "mine-sweeper-pro",
    "ar": "كانس الألغام المحترف",
    "en": "Minesweeper Pro",
    "description": "اثنتا عشرة خانة وأربعة وعشرون لغمًا: شبكة المحترفين حيث كل تخمين غير محسوب خيانة للمنطق.",
    "descriptionEn": "Minesweeper Pro — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "افتح بالخيار الآمن وضع الأعلام بالاستنتاج. لا تخمّن إلا مضطرًا.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "minesweeper",
      "hard",
      "logic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 560,
    "sizeKb": 12,
    "featured": true,
    "plays": 3599,
    "rating": 4.1
  },
  {
    "slug": "xo-classic",
    "ar": "إكس أو الكلاسيكية",
    "en": "Tic Tac Toe",
    "description": "ثلاثة في صف ضد حاسوب لا يخطئ: أقدم لعبة تفكير عرفتها البشرية، بخوارزمية كاملة.",
    "descriptionEn": "Tic Tac Toe — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط مربعًا للعب ❌. الحاسوب يلعب ⭕ بأفضل حركة ممكنة — حاول التعادل على الأقل.",
    "categories": [
      "kids",
      "two-player",
      "classic"
    ],
    "tags": [
      "xo",
      "tic-tac-toe",
      "family"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 520,
    "sizeKb": 6,
    "featured": false,
    "plays": 16436,
    "rating": 4.4
  },
  {
    "slug": "xo-neon",
    "ar": "إكس أو نيون",
    "en": "Neon XO",
    "description": "القواعد نفسها ببرق ونار: نسخة النيون من إكس أو لمن ملّ الرموز التقليدية.",
    "descriptionEn": "Neon XO — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط للعب ⚡ ضد 🔥. ثلاثة على خط تفوز.",
    "categories": [
      "arcade",
      "two-player"
    ],
    "tags": [
      "xo",
      "neon"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 520,
    "sizeKb": 7,
    "featured": false,
    "plays": 8373,
    "rating": 4.9
  },
  {
    "slug": "reaction-bolt",
    "ar": "سرعة البرق",
    "en": "Lightning Reflex",
    "description": "خمس جولات من الانتظار الأخضر: قِس سرعة استجابتك بالمللي ثانية ونافس أصدقاءك على المتوسط.",
    "descriptionEn": "Lightning Reflex — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "انتظر تحول الشاشة إلى الأخضر ثم اضغط بأسرع ما يمكنك. الضغط المبكر يلغي الجولة.",
    "categories": [
      "action",
      "brain"
    ],
    "tags": [
      "reaction",
      "reflex",
      "test"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 640,
    "height": 440,
    "sizeKb": 8,
    "featured": false,
    "plays": 5210,
    "rating": 4.2
  },
  {
    "slug": "reaction-focus",
    "ar": "بوابة التركيز",
    "en": "Focus Gate",
    "description": "ثماني جولات متتالية: اختبار تركيز أكثر منه اختبار سرعة، فالتعب في الجولة السادسة عدوّك الحقيقي.",
    "descriptionEn": "Focus Gate — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط عند الأخضر فقط. متوسطك النهائي هو نتيجتك.",
    "categories": [
      "brain",
      "puzzle"
    ],
    "tags": [
      "reaction",
      "focus",
      "endurance"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 640,
    "height": 440,
    "sizeKb": 9,
    "featured": false,
    "plays": 12347,
    "rating": 4.5
  },
  {
    "slug": "slide-fifteen",
    "ar": "لغز الخمسة عشر",
    "en": "Fifteen Puzzle",
    "description": "خمس عشرة بلاطة وخانة فارغة واحدة: اللغز الذي حيّر العالم في ١٨٨٠ وما يزال يصنع أبطالًا.",
    "descriptionEn": "Fifteen Puzzle — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط بلاطة مجاورة للفراغ لانزلاقها. رتّب الأرقام تصاعديًا.",
    "categories": [
      "puzzle",
      "brain"
    ],
    "tags": [
      "slide",
      "15-puzzle",
      "classic"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 520,
    "sizeKb": 10,
    "featured": false,
    "plays": 4484,
    "rating": 4.7
  },
  {
    "slug": "slide-eight",
    "ar": "لغز الثمانية السريع",
    "en": "Quick Eight",
    "description": "نسخة ٣×٣ الدافئة من لغز الانزلاق: تُحل في دقائق وتعلّم الأطفال تخطيط الحركة.",
    "descriptionEn": "Quick Eight — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "انقر بلاطة ملاصقة للفراغ. الهدف: ترتيب ١ إلى ٨.",
    "categories": [
      "kids",
      "puzzle"
    ],
    "tags": [
      "slide",
      "easy",
      "kids"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 520,
    "height": 520,
    "sizeKb": 11,
    "featured": false,
    "plays": 9821,
    "rating": 4
  },
  {
    "slug": "stroop-colors",
    "ar": "خِداع الألوان",
    "en": "Stroop Colors",
    "description": "كلمة «أحمر» مكتوبة بالحبر الأزرق: دماغك يقرأ وعينك ترى، وأيهما يفوز يحدد نتيجتك. اختبار ستروب الشهير بصورة لعبة.",
    "descriptionEn": "Stroop Colors — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "يمين/١ إن كان لون الحبر مطابقًا لمعنى الكلمة، ويسار/٢ إن لم يكن. ثلاثون ثانية.",
    "categories": [
      "brain",
      "puzzle"
    ],
    "tags": [
      "stroop",
      "focus",
      "tricky"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 640,
    "height": 440,
    "sizeKb": 12,
    "featured": false,
    "plays": 3358,
    "rating": 4.8
  },
  {
    "slug": "stroop-reverse",
    "ar": "انعكاس ستروب",
    "en": "Stroop Reverse",
    "description": "النسخة المعكوسة: حكِّم معنى الكلمة لا لونها. أصعب بخمس وعشرين ثانية مما تتوقع.",
    "descriptionEn": "Stroop Reverse — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "يمين = الكلمة تطابق لون الحبر، يسار = لا. نعم، التعليمات معاكسة للنسخة الأخرى عمدًا.",
    "categories": [
      "brain",
      "action"
    ],
    "tags": [
      "stroop",
      "hard",
      "reverse"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 640,
    "height": 440,
    "sizeKb": 6,
    "featured": false,
    "plays": 7695,
    "rating": 4.3
  },
  {
    "slug": "gold-clicker",
    "ar": "منجم الذهب",
    "en": "Gold Clicker",
    "description": "انقر العملة واشترِ فؤوسًا وعمالًا وديناميت: لعبة الخمول التي تكبر وأنت تشرب الشاي.",
    "descriptionEn": "Gold Clicker — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط الدائرة الذهبية لجمع العملات، واشترِ الترقيات من الأزرار أسفل الشاشة.",
    "categories": [
      "adventure",
      "kids"
    ],
    "tags": [
      "clicker",
      "idle",
      "gold"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 620,
    "sizeKb": 7,
    "featured": true,
    "plays": 3172,
    "rating": 4.6
  },
  {
    "slug": "energy-clicker",
    "ar": "مولّد الطاقة",
    "en": "Energy Clicker",
    "description": "ابنِ إمبراطورية كهرباء من نقرات: بطاريات وألواح شمسية ومفاعل ينتجون وأنت غائب.",
    "descriptionEn": "Energy Clicker — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "انقر المولّد واجمع الفولتات، ثم استثمر في الإنتاج التلقائي.",
    "categories": [
      "adventure",
      "arcade"
    ],
    "tags": [
      "clicker",
      "idle",
      "energy"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 620,
    "sizeKb": 8,
    "featured": false,
    "plays": 6599,
    "rating": 4.1
  },
  {
    "slug": "bubble-pop",
    "ar": "فرقعة الفقاعات",
    "en": "Bubble Pop",
    "description": "فقاعات تصعد بهدوء وفرقعتها بصوت مكتوم: لعبة الاسترخاء الأولى في الموقع، والنقاط للفقاعات الأصغر.",
    "descriptionEn": "Bubble Pop — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط الفقاعة قبل أن تخرج من الأعلى. الصغيرة تساوي نقاطًا أكثر.",
    "categories": [
      "kids",
      "mobile"
    ],
    "tags": [
      "bubble",
      "tap",
      "relax"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 640,
    "sizeKb": 9,
    "featured": false,
    "plays": 10526,
    "rating": 4.4
  },
  {
    "slug": "balloon-pop-fair",
    "ar": "فرقعة البالونات",
    "en": "Balloon Fair",
    "description": "مدينة ملاهٍ كاملة من البالونات الطائرة: فرقّعها قبل أن تهرب إلى السماء.",
    "descriptionEn": "Balloon Fair — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط البالونات الصاعدة. إن أفلتت عشرة انتهت الجولة.",
    "categories": [
      "kids",
      "arcade"
    ],
    "tags": [
      "balloon",
      "tap",
      "fair"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone",
    "width": 560,
    "height": 640,
    "sizeKb": 10,
    "featured": false,
    "plays": 4043,
    "rating": 4.9
  },
  {
    "slug": "meteor-guard",
    "ar": "حارس النيازك",
    "en": "Meteor Guard",
    "description": "نيازك صاعدة (نعم، صاعدة — الجاذبية هنا اقتراح) ومهمتك تفجيرها قبل الإفلات: نسخة الأكشن من سلسلة الفرقعة.",
    "descriptionEn": "Meteor Guard — a self-contained HTML5 build from the Voltade demo library.",
    "instructions": "اضغط النيزك لتفجيره. ثمانية إفلاتات تخسر المهمة.",
    "categories": [
      "action",
      "shooting"
    ],
    "tags": [
      "meteor",
      "fast",
      "defense"
    ],
    "developer": "Voltade Studio",
    "ageRating": "everyone_10",
    "width": 560,
    "height": 640,
    "sizeKb": 11,
    "featured": false,
    "plays": 16880,
    "rating": 4.2
  }
] as const;
