import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { withDatabase, introspect, type TestDatabase } from './helpers/database.js';
import { parsePrismaSchema } from '../src/tools/prisma-schema.js';
import { sqlType } from '../src/tools/ddl.js';
import { schemaPath, migrationsDir } from '../src/env.js';
import { seedDatabase } from '../src/seed/content.js';

/**
 * Schema parity: prisma/schema.prisma ↔ the committed SQL ↔ the live database.
 *
 * Voltade is schema-first, but the Prisma engine binaries cannot be downloaded in
 * every environment, so the migrations are generated by our own tool. That is
 * only safe if something *proves* the three artifacts agree — this file is that
 * proof, and it runs against a real PostgreSQL (PGlite) rather than a text diff:
 * it applies the migrations and then asks the database what it actually contains.
 *
 * What it catches:
 *  · a column in schema.prisma that the migration forgot (missing table/column);
 *  · a type that drifted (VARCHAR(30) → TEXT, INTEGER → BIGINT, enum → text);
 *  · a nullability change that would let the API insert a NULL into a NOT NULL;
 *  · an enum whose values no longer match the CHECK constraints and the TS union;
 *  · a column the database has that the schema does not (undeclared, unreviewed).
 */

/** Columns the hand-written migrations add on top of the Prisma schema. Every
 *  entry here is deliberate, documented in migration 0002, and asserted below. */
const DB_MANAGED_EXTRAS: Record<string, string[]> = {
  games: ['search_vector'],
  blog_posts: ['search_vector'],
};

/** Prisma's bookkeeping table — created by the migrator, not by the schema. */
const DB_MANAGED_TABLES = ['_prisma_migrations'];

let ctx: TestDatabase;
const schema = parsePrismaSchema(readFileSync(schemaPath(), 'utf8'));

type LiveColumn = {
  table: string;
  column: string;
  dataType: string;
  udtName: string;
  length: number | null;
  precision: number | null;
  scale: number | null;
  nullable: boolean;
  default: string | null;
};

/**
 * Full column metadata straight from information_schema. introspect() keeps a
 * deliberately small summary (type/nullable/default) because that is all the
 * migrator needs; a parity check has to compare VARCHAR *lengths* and NUMERIC
 * precision too, so it asks for them itself.
 */
async function liveColumns(ctx: TestDatabase): Promise<Map<string, LiveColumn>> {
  const rows = await ctx.conn.many<{
    tableName: string; columnName: string; dataType: string; udtName: string;
    length: number | null; precision: number | null; scale: number | null;
    isNullable: string; columnDefault: string | null;
  }>(
    `SELECT table_name AS "tableName", column_name AS "columnName", data_type AS "dataType",
            udt_name AS "udtName", character_maximum_length AS "length",
            numeric_precision AS "precision", numeric_scale AS "scale",
            datetime_precision AS "dtp", is_nullable AS "isNullable", column_default AS "columnDefault"
       FROM information_schema.columns WHERE table_schema = 'public'`,
  );
  const out = new Map<string, LiveColumn>();
  for (const r of rows) {
    out.set(`${r.tableName}.${r.columnName}`, {
      table: r.tableName,
      column: r.columnName,
      dataType: r.dataType,
      udtName: r.udtName,
      // timestamps report their precision in datetime_precision, not numeric_precision
      length: r.length,
      precision: r.precision ?? (r as unknown as { dtp: number | null }).dtp,
      scale: r.scale,
      nullable: r.isNullable === 'YES',
      default: r.columnDefault,
    });
  }
  return out;
}

/** Normalises a live information_schema column into the vocabulary sqlType() uses. */
function liveType(col: LiveColumn): string {
  switch (col.dataType) {
    case 'character varying':
      return `VARCHAR(${col.length ?? ''})`;
    case 'character':
      return `CHAR(${col.length ?? ''})`;
    case 'text':
      return 'TEXT';
    case 'ARRAY': {
      const inner = col.udtName.replace(/^_/, '');
      const map: Record<string, string> = { text: 'TEXT', varchar: 'VARCHAR', int4: 'INTEGER', int8: 'BIGINT', int2: 'SMALLINT' };
      return `${map[inner] ?? inner.toUpperCase()}[]`;
    }
    case 'USER-DEFINED':
      return `"${col.udtName}"`;
    case 'timestamp with time zone':
      return `TIMESTAMPTZ(${col.precision ?? 6})`;
    case 'timestamp without time zone':
      return `TIMESTAMP(${col.precision ?? 6})`;
    case 'date':
      return 'DATE';
    case 'jsonb':
      return 'JSONB';
    case 'json':
      return 'JSON';
    case 'boolean':
      return 'BOOLEAN';
    case 'integer':
      return 'INTEGER';
    case 'smallint':
      return 'SMALLINT';
    case 'bigint':
      return 'BIGINT';
    case 'real':
      return 'REAL';
    case 'double precision':
      return 'DOUBLE PRECISION';
    case 'numeric':
      return `DECIMAL(${col.precision ?? ''},${col.scale ?? ''})`;
    case 'tsvector':
      return 'TSVECTOR';
    default:
      return col.dataType.toUpperCase();
  }
}

beforeAll(async () => {
  process.env.SEED_ADMIN_PASSWORD = 'Voltade!2026';
  ctx = await withDatabase({ max: 2 });
  // A few assertions below (search matching, CHECK enforcement on a real rating)
  // need rows to look at, so the parity database is seeded too.
  await seedDatabase(ctx.db, { demo: true, onLog: () => {} });
}, 180_000);

afterAll(async () => {
  await ctx?.close();
});

describe('tables', () => {
  it('every Prisma model exists as a table', async () => {
    const live = await introspect(ctx.conn);
    const liveTables = Object.keys(live.tables);
    for (const model of schema.models) {
      expect(liveTables, `missing table for model ${model.name}`).toContain(model.table);
    }
  });

  it('the database has no undeclared tables', async () => {
    const live = await introspect(ctx.conn);
    const declared = new Set([...schema.models.map((m) => m.table), ...DB_MANAGED_TABLES]);
    const extra = Object.keys(live.tables).filter((t) => !declared.has(t));
    expect(extra, 'tables exist that schema.prisma does not declare').toEqual([]);
  });
});

describe('columns', () => {
  it('every scalar field exists with the expected type and nullability', async () => {
    const columns = await liveColumns(ctx);
    const problems: string[] = [];
    let checked = 0;

    for (const model of schema.models) {
      for (const field of model.fields) {
        if (field.isRelationField || schema.modelByName.has(field.type)) continue;
        const col = columns.get(`${model.table}.${field.column}`);
        if (!col) {
          problems.push(`${model.table}.${field.column}: column missing (field ${field.name})`);
          continue;
        }
        checked++;
        const expected = sqlType(field, schema);
        const actual = liveType(col);
        if (expected !== actual) problems.push(`${model.table}.${field.column}: type ${actual} ≠ schema ${expected}`);
        const expectedNullable = field.isOptional ? 'YES' : 'NO';
        const actualNullable = col.nullable ? 'YES' : 'NO';
        if (expectedNullable !== actualNullable) {
          problems.push(`${model.table}.${field.column}: nullable ${actualNullable} ≠ schema ${expectedNullable}`);
        }
      }
    }

    expect(problems, `${problems.length} column mismatches`).toEqual([]);
    expect(checked).toBeGreaterThan(400); // the schema has ~450 scalar columns
  });

  it('the database has no undeclared columns', async () => {
    const columns = await liveColumns(ctx);
    const declared = new Set<string>();
    for (const model of schema.models) {
      for (const f of model.fields) {
        if (f.isRelationField || schema.modelByName.has(f.type)) continue;
        declared.add(`${model.table}.${f.column}`);
      }
      for (const extra of DB_MANAGED_EXTRAS[model.table] ?? []) declared.add(`${model.table}.${extra}`);
    }
    // _prisma_migrations belongs to the migrator, not to the domain schema.
    const problems = [...columns.keys()].filter(
      (key) => !declared.has(key) && !DB_MANAGED_TABLES.includes(key.split('.')[0]!),
    );
    expect(problems).toEqual([]);
  });

  it('declares the generated search vectors as STORED tsvector columns', async () => {
    for (const [table, column] of Object.entries(DB_MANAGED_EXTRAS).flatMap(([t, cols]) => cols.map((c) => [t, c] as const))) {
      const row = await ctx.conn.one<{ dataType: string; isGenerated: string; definition: string | null }>(
        `SELECT data_type AS "dataType", is_generated AS "isGenerated", generation_expression AS "definition"
           FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name=$2`,
        [table, column],
      );
      expect(row, `${table}.${column} missing`).not.toBeNull();
      expect(row!.dataType).toBe('tsvector');
      expect(row!.isGenerated).toBe('ALWAYS');
      expect(row!.definition).toContain('to_tsvector');
      // 'simple', not 'english': the catalogue is Arabic-first and the english
      // stemmer would drop Arabic tokens entirely.
      expect(row!.definition).toContain("'simple'");
    }
  });
});

describe('enums', () => {
  it('every Prisma enum is a Postgres type with identical values in identical order', async () => {
    const live = await introspect(ctx.conn);
    const problems: string[] = [];
    for (const e of schema.enums) {
      const actual = live.enums[e.typeName];
      if (!actual) {
        problems.push(`${e.typeName}: type missing`);
        continue;
      }
      if (actual.join(',') !== e.values.join(',')) {
        problems.push(`${e.typeName}: db [${actual.join(',')}] ≠ schema [${e.values.join(',')}]`);
      }
    }
    expect(problems).toEqual([]);
    expect(Object.keys(live.enums).length).toBe(schema.enums.length);
  });

  it('has no orphan enum types', async () => {
    const live = await introspect(ctx.conn);
    const declared = new Set(schema.enums.map((e) => e.typeName));
    expect(Object.keys(live.enums).filter((t) => !declared.has(t))).toEqual([]);
  });
});

describe('indexes and constraints', () => {
  it('creates the unique indexes the dedupe and login paths depend on', async () => {
    const live = await introspect(ctx.conn);
    const required: [string, string][] = [
      ['games', 'games_source_hash_key'], // duplicate-import gate
      ['games', 'games_slug_key'],
      ['users', 'users_email_lower_key'], // case-insensitive login
      ['users', 'users_username_lower_key'],
      ['categories', 'categories_slug_key'],
      ['settings', 'settings_pkey'], // `key` is the primary key, not a separate unique
      ['daily_stats', 'daily_stats_day_dimension_key_key'], // the rollup upsert target
    ];
    for (const [table, index] of required) {
      expect(live.indexes[table] ?? [], `${table}: missing ${index}`).toContain(index);
    }
  });

  it('indexes the hot listing paths (20k+ games must not seq-scan)', async () => {
    const live = await introspect(ctx.conn);
    const games = live.indexes['games'] ?? [];
    // status+published_at is the homepage query; plays is "most played";
    // rating_avg is "top rated"; the GIN index backs full-text search.
    expect(games.some((i) => i.includes('status') && i.includes('published_at'))).toBe(true);
    expect(games.some((i) => i.includes('plays'))).toBe(true);
    expect(games.some((i) => i.includes('rating_avg'))).toBe(true);
    expect(games.some((i) => i.includes('search_vector'))).toBe(true);
    expect(games.length).toBeGreaterThanOrEqual(12);
  });

  it('applies the CHECK constraints from migration 0002', async () => {
    const checks = await ctx.conn.many<{ name: string; table: string }>(
      `SELECT conname AS name, relname AS table
         FROM pg_constraint c JOIN pg_class r ON r.oid = c.conrelid
        WHERE contype = 'c' AND r.relnamespace = 'public'::regnamespace`,
    );
    expect(checks.length).toBeGreaterThanOrEqual(20);
    const names = checks.map((c) => c.name);
    expect(names.some((n) => /rating|stars/i.test(n))).toBe(true);
    expect(names.some((n) => /plays|count/i.test(n))).toBe(true);
  });

  it('enforces them: an out-of-range rating is rejected by the database', async () => {
    const game = await ctx.conn.one<{ id: string }>(`SELECT id FROM games LIMIT 1`);
    const user = await ctx.conn.one<{ id: string }>(`SELECT id FROM users WHERE role_id IN (SELECT id FROM roles WHERE slug='user') LIMIT 1`);
    if (!game || !user) return; // a fresh, unseeded database: nothing to attach to
    await expect(
      ctx.conn.run(`INSERT INTO ratings (id, game_id, user_id, stars) VALUES ($1,$2,$3,9)`, ['r-bad', game.id, user.id]),
    ).rejects.toThrow(/check|constraint|stars/i);
  });

  it('enforces the foreign keys: a play for a missing game is rejected', async () => {
    await expect(
      ctx.conn.run(
        `INSERT INTO game_plays (game_id, device, started_at) VALUES ($1,'desktop',now())`,
        ['nonexistent_game_id_000000'],
      ),
    ).rejects.toThrow(/foreign key|violates/i);
  });
});

describe('search behaviour in the live database', () => {
  it('matches Arabic and English through the generated tsvector', async () => {
    const arabic = await ctx.conn.many<{ slug: string }>(
      `SELECT slug FROM games WHERE search_vector @@ plainto_tsquery('simple', $1)`,
      ['الثعبان'],
    );
    expect(arabic.map((g) => g.slug)).toContain('snake-volt');

    const english = await ctx.conn.many<{ slug: string }>(
      `SELECT slug FROM games WHERE search_vector @@ plainto_tsquery('simple', $1)`,
      ['pong'],
    );
    expect(english.map((g) => g.slug)).toContain('neon-pong');
  });

  it('is case-insensitive and ranks a title hit above a description hit', async () => {
    const rows = await ctx.conn.many<{ slug: string; rank: number }>(
      `SELECT slug, ts_rank(search_vector, plainto_tsquery('simple', $1))::float AS rank
         FROM games WHERE search_vector @@ plainto_tsquery('simple', $1) ORDER BY rank DESC`,
      ['2048'],
    );
    expect(rows.length).toBeGreaterThan(0);
    expect(rows[0]!.slug).toBe('volt-2048');
    expect(rows[0]!.rank).toBeGreaterThan(0);
  });
});

describe('migration files', () => {
  it('are recorded in _prisma_migrations in Prisma\u2019s own format', async () => {
    const rows = await ctx.conn.many<{ name: string; checksum: string; steps: number }>(
      `SELECT migration_name AS name, checksum, applied_steps_count AS steps FROM _prisma_migrations ORDER BY started_at`,
    );
    expect(rows.map((r) => r.name)).toEqual(['20260905120000_init', '20260905120200_search_and_constraints']);
    for (const r of rows) {
      expect(r.checksum).toMatch(/^[a-f0-9]{64}$/);
      expect(r.steps).toBe(1);
    }
  });

  it('are both present on disk with a provider lock', () => {
    const lock = readFileSync(join(migrationsDir(), 'migration_lock.toml'), 'utf8');
    expect(lock).toContain('postgresql');
    for (const dir of ['20260905120000_init', '20260905120200_search_and_constraints']) {
      expect(readFileSync(join(migrationsDir(), dir, 'migration.sql'), 'utf8').length).toBeGreaterThan(100);
    }
  });
});
